### ISSUE TITLE
Update skew and kurtosis edge case where len(array) == 1

### ISSUE THREAD

**Issue by phobson** [dask/crick#31]
Crick was originally written to be compatible with scipy ~1.7.

Now with a more modern scipy, skew and kurtosis return NaN when len(array) == 1.

xref: https://github.com/dask/crick/pull/27/files#diff-d44b0bb9b89b84dbf550af3a02d4f557b598d95e228fa00f002d75c03bc894beR24

**Comment by milesgranger** [comment]
closed by #39 (https://github.com/dask/crick/pull/39/commits/47fbdcd6c4e957a3a40eb290f3fd94dc0501c5f3)
