### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by NishkaDG** [dask/crick#61]
Hello,
Is there documentation available anywhere for how to use this package? I am most interested in the quantile function, but I have been unable to find a user guide or README for this package.
Thanks,

**Comment by phofl** [comment]
This is more a utility for us in dask, so docs aren’t a priority for us.
You want to interface directly with crick?

Nishka Dasgupta ***@***.***> schrieb am Di. 17. Sept. 2024 um
13:45:

**Comment by NishkaDG** [comment]
I would like to use the quantile function implemented with the tdigest algorithm, yes. This package was referenced in this paper: https://presentations.copernicus.org/EGU24/EGU24-8062_presentation-h573564.pdf . 
Does dask itself use crick?

**Comment by phofl** [comment]
Yes, dask uses crick for quantiles as well

Nishka Dasgupta ***@***.***> schrieb am Di. 17. Sept. 2024 um
14:54:

**Comment by NishkaDG** [comment]
Thanks!
